### ISSUE TITLE
bug: DNS not resolving service name to IP address

### ISSUE THREAD

**Issue by hydai** [second-state/microservice-rust-mysql#23] opened 2024-02-19 17:46 UTC
Related issue:
1. https://github.com/moby/moby/issues/47403
2. https://github.com/second-state/microservice-rust-mysql/pull/22

The current status:

1. WASM container cannot resolve the service name
2. The DNS server of docker-compose is still `127.0.0.11:53`
3. The `DNS_SERVER` magic is not working.
4. The wasi-socket component inside WasmEdge is not changed.
5. We should check all used wasi-socket crates to see if there are some modifications related to this problem <-- We are here now

**Comment by aalonsolopez** [comment] 2024-02-20 10:18
My understanding of Rust is super basic, but I was planning on learning it... Something in which I can help?

**Comment by hydai** [comment] 2024-02-20 15:52
The related code is under these three crates: https://github.com/second-state/microservice-rust-mysql/blob/main/Cargo.toml#L11-L13

If you would like to dig into the details, please check the error caused in the microservice-rust-mysql and find which crates are highly related to the error.

**Comment by aalonsolopez** [comment] 2024-02-20 16:20
Perfect!

**Comment by aalonsolopez** [comment] 2024-02-21 16:55
Can you assign this to me? i will try my best to solve it. If I can't, I'll let you know.

**Comment by hydai** [comment] 2024-02-21 17:07
Sure. Here you go.

**Comment by aalonsolopez** [comment] 2024-02-26 12:54
I'm nearly 99% sure that the problem is with tokio_wasi crate, making some tests rn

**Comment by aalonsolopez** [comment] 2024-02-26 13:27
As you can see in https://github.com/WasmEdge/tokio/commit/f6dae1c8cb41271c75516b7fe8ce9dcb49ab960c this problem seems to be solved, but anyway it still failing. Apparently, it has like version conflicts because the repo references 1.28.2 as the latest version but it's not published on crates.io

**Comment by aalonsolopez** [comment] 2024-03-06 20:05
#24 has the solution

**Closed as completed** 2024-03-07 15:54 UTC
